### ISSUE TITLE
req.session.username checked is need for /checkout/error page

### ISSUE THREAD

**Issue by dickylai** [ierg4210/shop66#2]
[parameter tempering] I have created accountA and accountB. First, I use accountA to create a payment and press cancel. I logout accountA and login to accountB. I copy the payment error link in accountA and try to go to the link with my accountB credentials. I can get into the page with accountB and press "retry payment" to pay the money. After payment success, it will shown in accountA. I think you lack a checking between the info with req.session in your database. You can add the checking with your database in checkout.get('/error') in line 97-99 in checkout.js.

**Comment by ericwong3** [comment]
No not necessary, although the idea of "error" is unappealing, but actually not validating it has its use. Think about a scenario where A placed an order, and then want to ask B to do the payment, then validation in fact prohibit this. 
Although the better way would be, instead of forwarding the user directly to PayPal, ask whether user want to pay him/herself or ask others to pay, for the former one send him/her to PayPal the same way as now, and for the later one, present the link to the user and let him/her send the link to the other guy.
So as a conclusion, still, not necessary

**Comment by dickylai** [comment]
For your scenario in the first paragraph, why don't A just give the paypal payment link to B? lol

Think about a scenario, as A will not notice if the payment owner is A or B on paypal page, it is better to check and reject if the payment error is not generated by payment of A before showing the error page giving the chance to checkout in paypal for other users unintentionally. It is more secure for A.

**Comment by ericwong3** [comment]
First para: yeah you can, you can either send the error page link or you can send the paypal link to your friend, but still this doesn't mean its vulnerable, its just that the application allows you to do so in an ugly way (error page link).
Well... i'd say if someone "unintentionally checkout for others", and in addition does not check the paypal order list of the left, moreover not noticing the incorrect amount, then that guy does not suit for online shopping
